name: build, test

run-name: web team running application 🚀

on:
  push:
    branches: [ test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      - name: Docker mongoDB
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./backend/docker-compose.yml"

      - name: Install dependencies
        run: npm run get:dependencies

      - name: Build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      - name: Docker mongoDB
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./backend/docker-compose.yml"

      - name: Install dependencies
        run: npm run get:dependencies

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test
